#HACKBIOCODING INTERNSHIP

#STAGE 0

# Storing personal details in variables as shown below "name" is variable and the information store in this variable is "MUHAMMAD FAIZAN KHAN"
"
name = "Muhammad Faizan Khan"
slack_username = "Faizan"
email = "faizanjeee@hotmail.com"
hobby = "Learning Bioinformatics Skills"
country = "Pakistan"
discipline = "Biomedical Sciences"
preferred_language = "Python"

# Printing the organized output in a readable way by using print command below you can see after bracket "Name" is the string which output "Name" but the variable "name" output the information store in that variable "MUHAMMAD FAIZAN KHAN"

print("User Information:")
print("Name:", name)
print("Slack Username:", slack_username)
print("Email:", email)
print("Hobby:", hobby)
print("Country:", country)
print("Discipline:", discipline)
print("Preferred Programming Language:", preferred_language)
